kafkaPool: nav-dev
dbTier: db-f1-micro
dbAutoresizeDisk: false
limitsCpu: 2000m
limitsMemory: 1Gi
requestsCpu: 100m
requestsMemory: 256Mi
enhetsregisteretHost: arbeidsgiver-mock-enhetsregisteret.intern.dev.nav.no
enhetsregisteretUrl: https://arbeidsgiver-mock-enhetsregisteret.intern.dev.nav.no
