apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pia-sykefravarsstatistikk"
  namespace: "pia"
  labels:
    team: "pia"
spec:
  image: {{image}}
  resources:
    limits:
      cpu: {{limitsCpu}}
      memory: {{limitsMemory}}
    requests:
      cpu: {{requestsCpu}}
      memory: {{requestsMemory}}
  liveness:
    path: "/internal/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  prometheus:
    enabled: true
    path: "/metrics"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: loki
        - id: elastic
  accessPolicy:
    outbound:
      rules:
        - application: arbeidsgiver-altinn-tilganger
          namespace: fager
      external:
        - host: {{ enhetsregisteretHost }}
    inbound:
      rules:
        - application: min-ia
          namespace: pia
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: {{dbAutoresizeDisk}}
        tier: {{dbTier}}
        databases:
          - name: "pia-sykefravarsstatistikk-db"
  kafka:
    pool: {{kafkaPool}}
  env:
    - name: ENHETSREGISTERET_URL
      value: {{ enhetsregisteretUrl }}
    - name: ALTINN_RETTIGHET_SERVICE_CODE
      value: "3403"
    - name: ALTINN_RETTIGHET_SERVICE_EDITION
      value: "{{ serviceEdition }}"
    - name: ALTINN_TILGANGER_PROXY_URL
      value: http://arbeidsgiver-altinn-tilganger.fager
