apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: sykefravarsstatistikk-sektor-v1
  namespace: pia
  labels:
    team: pia
spec:
  pool: {{kafkaPool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact, compact,delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 720  # 30 dager
  acl:
    - team: pia
      application: pia-sykefravarsstatistikk
      access: readwrite   # read, write, readwrite
    - team: pia
      application: lydia-api
      access: read # read, write, readwrite
    - team: pia
      application: pia-devops
      access: read
    - team: team-dialog
      application: sf-sykefravarsstatistikk-sektor
      access: read
